[package]
name = "advent_of_code_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.1"
peg = "0.7.0"
[[bin]]
name = "2019_02_01"
path = "2019_02_01.rs"
